import { useEffect, useMemo, useState } from 'react';
import {
  KeyboardAvoidingView,
  Platform,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import { Snackbar } from 'react-native-paper';
import { useRouter } from 'expo-router';
import { useTranslation } from 'react-i18next';
import type { TFunction } from 'i18next';
import { useForm, Controller } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { ChevronDown, ChevronUp } from 'lucide-react-native';
import { useFarmStore } from '../../stores/farm';
import { supabase } from '../../lib/supabase';
import { Card, TextInput, Button } from '../../components/ui';
import { track, FUNNEL } from '../../lib/analytics';
import { colors, spacing, typography, radius } from '../../theme/tokens';

type Shed = {
  id: string;
  shed_name: string;
  poultry_type: 'broiler' | 'layer' | 'breeder';
};

function makeBatchSchema(t: TFunction) {
  return z.object({
    breed_name: z.string().min(1, t('setup.batches.errors.breed_required')),
    placement_date: z
      .string()
      .regex(/^\d{4}-\d{2}-\d{2}$/, t('setup.batches.errors.date_format')),
    opening_bird_count: z
      .string()
      .refine((v) => /^[0-9]+$/.test(v) && parseInt(v) > 0, {
        message: t('setup.batches.errors.bird_count_valid'),
      }),
    source_supplier: z.string().min(1, t('setup.batches.errors.supplier_required')),
    cost_per_bird: z
      .string()
      .refine((v) => /^[0-9]+(\.[0-9]{1,2})?$/.test(v) && parseFloat(v) >= 0, {
        message: t('setup.batches.errors.cost_valid'),
      }),
  });
}

type BatchFormData = z.infer<ReturnType<typeof makeBatchSchema>>;

function getTodayISO() {
  const d = new Date();
  const yyyy = d.getFullYear();
  const mm = String(d.getMonth() + 1).padStart(2, '0');
  const dd = String(d.getDate()).padStart(2, '0');
  return `${yyyy}-${mm}-${dd}`;
}

function ShedBatchForm({
  shed,
  farmId,
  onSaved,
}: {
  shed: Shed;
  farmId: string;
  onSaved: () => void;
}) {
  const { t } = useTranslation();
  const [collapsed, setCollapsed] = useState(false);
  const [saved, setSaved] = useState(false);
  const [snackVisible, setSnackVisible] = useState(false);
  const [snackMessage, setSnackMessage] = useState('');
  const batchSchema = useMemo(() => makeBatchSchema(t), [t]);

  const {
    control,
    handleSubmit,
    formState: { errors, isSubmitting },
  } = useForm<BatchFormData>({
    resolver: zodResolver(batchSchema),
    defaultValues: {
      breed_name: '',
      placement_date: getTodayISO(),
      opening_bird_count: '',
      source_supplier: '',
      cost_per_bird: '',
    },
  });

  const onSubmit = async (values: BatchFormData) => {
    const openingCount = parseInt(values.opening_bird_count);
    const { error } = await supabase.from('batches').insert({
      shed_id: shed.id,
      farm_id: farmId,
      breed_name: values.breed_name,
      poultry_type: shed.poultry_type,
      placement_date: values.placement_date,
      opening_bird_count: openingCount,
      current_bird_count: openingCount,
      source_supplier: values.source_supplier,
      cost_per_bird: parseFloat(values.cost_per_bird),
      status: 'active',
      // batch_code is generated by DB trigger — do NOT supply it
    });

    if (error) {
      setSnackMessage(error.message ?? t('setup.batches.save_failed'));
      setSnackVisible(true);
      return;
    }
    void track(FUNNEL.FIRST_BATCH_CREATED, { shed_id: shed.id });
    setSaved(true);
    setCollapsed(true);
    onSaved();
  };

  return (
    <>
      <Card style={styles.shedCard}>
        <Pressable
          style={styles.shedHeader}
          onPress={() => setCollapsed((c) => !c)}
          accessibilityRole="button"
          accessibilityLabel={t('setup.batches.toggle_a11y', { name: shed.shed_name })}
        >
          <View>
            <Text style={styles.shedName}>{shed.shed_name}</Text>
            <Text style={styles.shedMeta}>
              {t(`setup.poultry_type.${shed.poultry_type}`)}
              {saved ? ` · ${t('setup.batches.batch_saved')}` : ''}
            </Text>
          </View>
          {collapsed ? (
            <ChevronDown size={20} color={colors.body} />
          ) : (
            <ChevronUp size={20} color={colors.body} />
          )}
        </Pressable>

        {!collapsed && (
          <View style={styles.batchForm}>
            <Controller
              control={control}
              name="breed_name"
              render={({ field: { onChange, value } }) => (
                <TextInput
                  label={t('setup.batches.breed_name')}
                  value={value}
                  onChangeText={onChange}
                  autoCapitalize="words"
                  placeholder={t('setup.batches.breed_name_placeholder')}
                  error={errors.breed_name?.message}
                />
              )}
            />

            <Controller
              control={control}
              name="placement_date"
              render={({ field: { onChange, value } }) => (
                <TextInput
                  label={t('setup.batches.placement_date')}
                  value={value}
                  onChangeText={onChange}
                  keyboardType="numbers-and-punctuation"
                  placeholder={t('setup.batches.placement_date_placeholder')}
                  error={errors.placement_date?.message}
                />
              )}
            />

            <Controller
              control={control}
              name="opening_bird_count"
              render={({ field: { onChange, value } }) => (
                <TextInput
                  label={t('setup.batches.opening_bird_count')}
                  value={value}
                  onChangeText={onChange}
                  keyboardType="number-pad"
                  placeholder={t('setup.batches.opening_bird_count_placeholder')}
                  error={errors.opening_bird_count?.message}
                />
              )}
            />

            <Controller
              control={control}
              name="source_supplier"
              render={({ field: { onChange, value } }) => (
                <TextInput
                  label={t('setup.batches.source_supplier')}
                  value={value}
                  onChangeText={onChange}
                  autoCapitalize="words"
                  placeholder={t('setup.batches.source_supplier_placeholder')}
                  error={errors.source_supplier?.message}
                />
              )}
            />

            <Controller
              control={control}
              name="cost_per_bird"
              render={({ field: { onChange, value } }) => (
                <TextInput
                  label={t('setup.batches.cost_per_bird')}
                  value={value}
                  onChangeText={onChange}
                  keyboardType="decimal-pad"
                  placeholder={t('setup.batches.cost_per_bird_placeholder')}
                  error={errors.cost_per_bird?.message}
                />
              )}
            />

            <Button
              label={saved ? t('setup.batches.saved') : t('setup.batches.save_batch')}
              variant={saved ? 'outlineDark' : 'primary'}
              onPress={handleSubmit(onSubmit)}
              loading={isSubmitting}
              disabled={saved || isSubmitting}
              fullWidth
            />
          </View>
        )}
      </Card>

      <Snackbar
        visible={snackVisible}
        onDismiss={() => setSnackVisible(false)}
        duration={4000}
        style={styles.snackbar}
      >
        {snackMessage}
      </Snackbar>
    </>
  );
}

export default function BatchesSetup() {
  const router = useRouter();
  const { t } = useTranslation();
  const currentFarm = useFarmStore((s) => s.currentFarm);
  const [sheds, setSheds] = useState<Shed[]>([]);
  const [savedCount, setSavedCount] = useState(0);

  useEffect(() => {
    if (!currentFarm?.id) return;
    supabase
      .from('sheds')
      .select('id,shed_name,poultry_type')
      .eq('farm_id', currentFarm.id)
      .order('created_at')
      .then(({ data }) => setSheds(data ?? []));
  }, [currentFarm?.id]);

  const handleFinish = () => {
    router.replace('/setup/success');
  };

  const handleSkip = () => {
    router.replace('/(tabs)/dashboard');
  };

  return (
    <KeyboardAvoidingView
      style={styles.root}
      behavior={Platform.OS === 'ios' ? 'padding' : undefined}
    >
      <ScrollView
        contentContainerStyle={styles.scroll}
        keyboardShouldPersistTaps="handled"
      >
        <Text style={styles.sub}>
          {t('setup.batches.intro')}
        </Text>

        {sheds.map((shed) => (
          <ShedBatchForm
            key={shed.id}
            shed={shed}
            farmId={currentFarm?.id ?? ''}
            onSaved={() => setSavedCount((c) => c + 1)}
          />
        ))}

        {sheds.length === 0 && (
          <Card style={styles.noShedsCard}>
            <Text style={styles.noShedsText}>
              {t('setup.batches.no_sheds')}
            </Text>
          </Card>
        )}

        <Button
          label={t('setup.batches.go_to_dashboard')}
          variant="primary"
          onPress={handleFinish}
          fullWidth
          style={styles.dashboardBtn}
        />

        <Pressable
          onPress={handleSkip}
          style={styles.skipBtn}
          accessibilityRole="button"
          accessibilityLabel={t('setup.batches.skip')}
        >
          <Text style={styles.skipText}>{t('setup.batches.skip')}</Text>
        </Pressable>
      </ScrollView>
    </KeyboardAvoidingView>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.canvasSoft },
  scroll: {
    flexGrow: 1,
    padding: spacing.lg,
    gap: spacing.lg,
  },
  sub: {
    ...typography.bodyMd,
    color: colors.body,
  },
  shedCard: { gap: spacing.md },
  shedHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    minHeight: 44,
  },
  shedName: {
    ...typography.bodyMdStrong,
    color: colors.ink,
  },
  shedMeta: {
    ...typography.caption,
    color: colors.body,
    marginTop: spacing.xs,
  },
  batchForm: {
    gap: spacing.lg,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.mute,
    marginTop: spacing.sm,
  },
  noShedsCard: {},
  noShedsText: {
    ...typography.bodyMd,
    color: colors.body,
    textAlign: 'center',
  },
  dashboardBtn: {},
  skipBtn: {
    alignSelf: 'center',
    paddingVertical: spacing.md,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  skipText: {
    ...typography.bodySm,
    color: colors.body,
    textDecorationLine: 'underline',
  },
  snackbar: { backgroundColor: colors.ink },
});
